GET http://localhost:3000/api/service
Content-Type: application/json
Authorization: Bearer ya29.a0AcM612wOmYxdEcZMkOhQ0PYhdcN_qyFFzRDcWTK1wXGiWQNFAIhwbyU8zhdyDBF34eUpbb3IYJHLEJInIP-m6UXepe-XdyMesGberU4TpDR_LBIjvkdZ8r6rIvfH_nleQg8M_SDysHB_6R4vUoMcnWnrrfBMFvZaUQSDZAclaCgYKAS8SAQ4SFQHGX2MisXgK2L1ithf6GSL_kA1HBg0175