main = ".worker-next/index.mjs"
name = "akraft"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

minify = true

routes = [{ pattern = "akraft.net", custom_domain = true }]

# wrangler.toml (wrangler v3.79.0^)
# [observability.logs]

[observability]
enabled = true
